### ISSUE TITLE
Significant blank space after fast scrolling

### ISSUE THREAD

**Issue by lisa761** [lisa761/OpenRefine#1]
When fast scrolling, the total size allowed is fixed to 100. The rows are rendered by using the `scrollTop` method and then calculating the page number. The `modifiedScrollPosition` ensures that the new `top` for `first-row` is not the`scrollTop` value but the predicted value for where that page number would start. This ensures that the correct row (as correct as it could be with predictions with dynamic heights) corresponding to the scrollbar is set into view by setting the `scrollTop` to it's previous value (as opposed to setting it as the height for `first-row` which would make rows loaded after speed scrolling always start from the first row, like 101st or 401st).

The problem with this is that sometimes, on scrolling fast, the calculated row could be, say, 998. So you only have rows 998, 999 and 1000 present on the screen, while the rest of it is blank. This should not be the case.

The starting row, instead of always being hard-coded (101st, 201st etc.) should be calculated according to which row would come into view. This will make sure that the screen never has a blank space after scrolling fast.

**Comment by lisa761** [comment]
Fixed in the main PR here: https://github.com/OpenRefine/OpenRefine/pull/2746/commits/52891c9c273cd011d64ba0f1756ad3095ec057c4

**Comment by tfmorris** [comment]
With the latest commit the characteristics of the problem changed, but I'm still seeing occasions where the screen doesn't fully repaint. Screenshots from two examples are included below. For the first example, the last URL requested was http://127.0.0.1:3333/command/core/get-rows?project=2321259574266&start=1089&limit=100

The first examples was both generated using mouse scroll wheel scrolling and the second with the Page Down key, so it looks like both are affected. I had the Javascript console open during testing, but didn't see any useful debug messages or errors, just these warnings about timing:

```
[Violation] 'readystatechange' handler took 1018ms project-bundle.js:9636 
[Violation] 'readystatechange' handler took 907ms project-bundle.js:9636 
[Violation] 'readystatechange' handler took 966ms project-bundle.js:9636 
[Violation] 'readystatechange' handler took 1067ms project-bundle.js:9636 
[Violation] 'readystatechange' handler took 962msproject-bundle.js:9636 
[Violation] 'readystatechange' handler took 1251ms project-bundle.js:9636 

```
![Screen Shot 2020-08-07 at 5 33 57 PM](https://user-images.githubusercontent.com/82178/89690519-b33ce400-d8d4-11ea-988b-86d07d0698f9.png)
![Screen Shot 2020-08-07 at 5 42 27 PM](https://user-images.githubusercontent.com/82178/89690837-77564e80-d8d5-11ea-914c-74bd3d19c106.png)

**Comment by lisa761** [comment]
Hey @tfmorris, there could be two reasons why that is happening:

1. The scroll event was too fast to detect the visibility of the row containing `load-next-set` class and hence the corresponding load functions weren't called at all.
2. The rendering speed causes the rows to load slower than the time taken for the user to reach the bottom of the loaded set.

In case the rows didn't load even after staying in the same position for a while, it is most likely the 1st case and is separate from this commit (since this was added only for fast scrolling which is the case when only the row with either `first-row` or `last-row` class is visible on the screen). I am looking into limiting the loading functions and seeing what all changes I could make in the `setTimeOut` function like you mentioned in the last review of the main PR. That should solve this problem. Although would it be possible for you to add a screen recording of this case so that I could be sure I have gotten it right?
